// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poke.Persistence.Data;

#nullable disable

namespace Poke.Persistence.Data
{
    [DbContext(typeof(FavoriteDbContext))]
    [Migration("20220429141558_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Poke.Persistence.Models.FavoritePokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PokemonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PokemonId");

                    b.ToTable("FavoritePokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
